services:
  - type: web
    name: encuesta-quito-septiembre-2025
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
      - key: ASSET_ID_PICHINCHA
        sync: false
      - key: API_TOKEN
        sync: false
      - key: NOMBRE_PROYECTO_QUITO
        value: Encuesta Quito - Septiembre - 2025
      - key: CAMPO_ENCUESTADOR
        value: C_digo_encuestador
      - key: CAMPO_SUPERVISOR
        value: C_digo_Supervisor
      - key: META_ENCUESTAS_QUITO
        value: 1200
      - key: CACHE_TTL_SEGUNDOS
        value: 90
